// Export pages
export '/login/login_list_view/login_list_view_widget.dart'
    show LoginListViewWidget;
export '/dashboard/dashboard_list_view/dashboard_list_view_widget.dart'
    show DashboardListViewWidget;
export '/home/home_in_projact_list_view/home_in_projact_list_view_widget.dart'
    show HomeInProjactListViewWidget;
export '/approved/approved_list_view/approved_list_view_widget.dart'
    show ApprovedListViewWidget;
export '/car/residents_cars/residents_cars_widget.dart'
    show ResidentsCarsWidget;
export '/user/user_list_view/user_list_view_widget.dart'
    show UserListViewWidget;
export '/car/residents_cars_detail/residents_cars_detail_widget.dart'
    show ResidentsCarsDetailWidget;
export '/user/user_detail_list_view/user_detail_list_view_widget.dart'
    show UserDetailListViewWidget;
export '/car/externalvehicle/externalvehicle_widget.dart'
    show ExternalvehicleWidget;
export '/car/externalvehicle_detail/externalvehicle_detail_widget.dart'
    show ExternalvehicleDetailWidget;
export '/setting/setting_list_view/setting_list_view_widget.dart'
    show SettingListViewWidget;
export '/dashboard/registered_list_view/registered_list_view_widget.dart'
    show RegisteredListViewWidget;
export '/dashboard/registered_cars_list_view/registered_cars_list_view_widget.dart'
    show RegisteredCarsListViewWidget;
export '/dashboard/visitors_car_list_view/visitors_car_list_view_widget.dart'
    show VisitorsCarListViewWidget;
export '/home/home_detail_list_view/home_detail_list_view_widget.dart'
    show HomeDetailListViewWidget;
export '/manageproject/manageproject/manageproject_widget.dart'
    show ManageprojectWidget;
export '/manageproject/project_detail/project_detail_widget.dart'
    show ProjectDetailWidget;
